language: c
compiler:
  - gcc
script:
  - autoreconf -i
  - ./configure
  - make
after_success:
  - make check || exit 1
before_install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo sh -c "echo 'deb https://labs.consol.de/repo/testing/ubuntu precise main' >> /etc/apt/sources.list"
  - wget -q "https://labs.consol.de/repo/stable/RPM-GPG-KEY" -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install autoconf
  - sudo apt-get install build-essential
  - sudo apt-get install libcppunit-dev
  - sudo apt-get install naemon-dev
notifications:
  irc:
    channels:
      - "chat.freenode.net#naemon-devel"
    on_success: change
    on_failure: always
    skip_join: true
