sudo: required
dist: xenial
language: c
compiler:
  - gcc
script:
  - autoreconf -i
  - ./configure
  - make
after_success:
  - make check || exit 1
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/tests/tools"
  - export CUKE_UNIXCAT_PATH=$TRAVIS_BUILD_DIR/src/unixcat
  - export CUKE_LIVESTATUS_PATH=$TRAVIS_BUILD_DIR/src/.libs/livestatus.so
  - cucumber ./tests -t ~@skip -t ~@unreliable --strict || exit 1
  - LIVESTATUS_TCP=1 cucumber ./tests -t ~@skip -t ~@unreliable --strict || exit 1
before_install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/naemon:/daily/xUbuntu_$(lsb_release -rs)/ ./' >> /etc/apt/sources.list"
  - wget -q "https://build.opensuse.org/projects/home:naemon:daily/public_key" -O - | sudo apt-key add -
  - sudo aptitude update
  - sudo apt-get install autoconf
  - sudo apt-get install build-essential
  - sudo apt-get install libcppunit-dev
  - sudo apt-get install libglib2.0-dev
  - sudo apt-get install naemon-dev
  - sudo apt-get install naemon-core
  - sudo apt-get install ruby ruby-dev
  - gem install cucumber:1.3.18 websocket-driver:0.7.0 nokogiri:1.6.0 rack:1.6.5 rack-test:0.7.0 capybara:2.1.0 public_suffix:2.0.5 xpath:2.0 rspec:2.14.1 parallel_tests syntax:1.0.0 cliver:0.3.2
  - pyenv global 3.7
notifications:
  irc:
    channels:
      - "chat.freenode.net#naemon-devel"
    on_success: change
    on_failure: always
    skip_join: true
