post:
        steps: |
                # Install requirements for cucumber test
                if [ -f /usr/bin/systemctl ]; then
                        gem install cucumber:1.3.6 nokogiri:1.6.0 rack:1.6.5 capybara:2.1.0 poltergeist:1.11.0 rspec:2.14.1 parallel_tests syntax:1.0.0 --no-document
                else
                        gem2.0 install cucumber:1.3.6 nokogiri:1.6.0 rack:1.6.5 capybara:2.1.0 poltergeist:1.11.0 rspec:2.14.1 parallel_tests syntax:1.0.0 --no-rdoc --no-ri
                fi
                # Run cucumber tests
                mkdir -p /mnt/logs
                cd /mnt/git
                autoreconf -is
                ./configure --with-naemon-config-dir=/opt/monitor/etc/mconf \
                --with-broker-module-options="hidden_custom_var_prefix=OP5SECRET_ pnp_path=/opt/monitor/op5/pnp/perfdata /opt/monitor/var/rw/live"
                make
                ulimit -c unlimited
                echo "core ulimit: \$(ulimit -c)"
                export CUKE_SCREEN_DIR=/mnt/logs/screenshots
                export CUKE_CLOBBER_PATH=/mnt/git/tests/tools/ls-clobber
                export CUKE_UNIXCAT_PATH=/mnt/git/src/unixcat
                export CUKE_LIVESTATUS_PATH=/mnt/git/src/.libs/livestatus.so
                cucumber /mnt/git/tests -t ~@skip -t ~@unreliable --strict --format html --out /mnt/logs/cucumber.html --format pretty
